version: '3.6'

services:
  myredis1-master:
    image: redis:5
    ports:
      - "7000:7000"
    volumes:
      - ./docker-data/redis-1-master.conf:/usr/local/etc/redis/redis-master.conf
    command: redis-server /usr/local/etc/redis/redis-master.conf
    networks:
      app_net:
        ipv4_address: 173.17.1.2

  myredis1-slave:
    image: redis:5
    ports:
      - "8000:8000"
    volumes:
      - ./docker-data/redis-1-slave.conf:/usr/local/etc/redis/redis-slave.conf
    command: redis-server /usr/local/etc/redis/redis-slave.conf
    networks:
      app_net:
        ipv4_address: 173.17.1.3


  myredis2-master:
    image: redis:5
    ports:
      - "7001:7001"
    volumes:
      - ./docker-data/redis-2-master.conf:/usr/local/etc/redis/redis-master.conf
    command: redis-server /usr/local/etc/redis/redis-master.conf
    networks:
      app_net:
        ipv4_address: 173.17.2.2
  
  myredis2-slave:
    image: redis:5
    ports:
      - "8001:8001"
    volumes:
      - ./docker-data/redis-2-slave.conf:/usr/local/etc/redis/redis-slave.conf
    command: redis-server /usr/local/etc/redis/redis-slave.conf
    networks:
      app_net:
        ipv4_address: 173.17.2.3




  myredis3-master:
    image: redis:5
    ports:
      - "7002:7002"
    volumes:
      - ./docker-data/redis-3-master.conf:/usr/local/etc/redis/redis-master.conf
    command: redis-server /usr/local/etc/redis/redis-master.conf
    networks:
      app_net:
        ipv4_address: 173.17.3.2

  myredis3-slave:
    image: redis:5
    ports:
      - "8002:8002"
    volumes:
      - ./docker-data/redis-3-slave.conf:/usr/local/etc/redis/redis-slave.conf
    command: redis-server /usr/local/etc/redis/redis-slave.conf
    networks:
      app_net:
        ipv4_address: 173.17.3.3


  redis-cluster-setup:
    image: redis:5
    command: sh -c "
      sleep 5
      && yes yes | redis-cli
      --cluster create 173.17.1.2:7000 173.17.2.2:7001 173.17.3.2:7002 
      173.17.1.3:8000 173.17.2.3:8001 173.17.3.3:8002
      --cluster-replicas 1
      && redis-cli --cluster check 173.17.1.2:7000"
    networks:
      app_net:
    depends_on:
      - myredis1-master
      - myredis1-slave
      - myredis2-master 
      - myredis2-slave
      - myredis3-master
      - myredis3-slave

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16
