version: '3.6'

services:
  myredis1-master:
    image: redis:5
    ports:
      - "7000:7000"
    volumes:
      - ./docker-data/redis-1-master.conf:/usr/local/etc/redis/redis-master.conf
    command: redis-server /usr/local/etc/redis/redis-master.conf
    networks:
      app_net:
        ipv4_address: 173.18.1.2

  myredis2-master:
    image: redis:5
    ports:
      - "7001:7001"
    volumes:
      - ./docker-data/redis-2-master.conf:/usr/local/etc/redis/redis-master.conf
    command: redis-server /usr/local/etc/redis/redis-master.conf
    networks:
      app_net:
        ipv4_address: 173.18.2.2

  myredis3-master:
    image: redis:5
    ports:
      - "7002:7002"
    volumes:
      - ./docker-data/redis-3-master.conf:/usr/local/etc/redis/redis-master.conf
    command: redis-server /usr/local/etc/redis/redis-master.conf
    networks:
      app_net:
        ipv4_address: 173.18.3.2

  redis-cluster-setup:
    image: redis:5
    command: sh -c "
      sleep 5
      && yes yes | redis-cli
      --cluster create 173.18.1.2:7000 173.18.2.2:7001 173.18.3.2:7002 
      --cluster-replicas 0
      && redis-cli --cluster check 173.18.1.2:7000"
    networks:
      app_net:
    depends_on:
      - myredis1-master
      - myredis2-master 
      - myredis3-master

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16
